name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: email_service
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      mailhog:
        image: mailhog/mailhog
        ports:
          - 1025:1025
          - 18025:18025

    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/email_service
      PYTHONPATH: .
      SMTP_HOST: mailhog
      SMTP_PORT: 1025
      SMTP_USER: no-reply@example.com
      SMTP_PASSWORD: password
      PROJECT_NAME: Email Microservice
      VERSION: 1.0.0

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest
